// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 唤起模式：manual 默认；followFinder 独立于快捷键。
 */
export type Activation = "manual" | "followFinder";
