// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 仅两种 AI 策略，只约束 AI；手动终端直通。
 */
export type AiPolicy = "yolo" | "readOnlyAutoConfirmChanges";
