// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildInfo } from "./BuildInfo";
import type { ContextSnapshot } from "./ContextSnapshot";
import type { HostState } from "./HostState";
import type { PermissionSnapshot } from "./PermissionSnapshot";
import type { PlatformCapabilities } from "./PlatformCapabilities";
import type { SettingsSnapshot } from "./SettingsSnapshot";
import type { StorageStatus } from "./StorageStatus";

/**
 * `app_bootstrap`：窗口角色由宿主注入，不带凭据或全部日志。
 */
export type AppBootstrap = { buildInfo: BuildInfo, hostState: HostState, windowRole: string, storage: StorageStatus, settings: SettingsSnapshot, permissions: PermissionSnapshot, platform: PlatformCapabilities, context: ContextSnapshot | null, };
