// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostState } from "./HostState";
import type { Revision } from "./Revision";

/**
 * 低频事件载荷（settings.changed / permissions.changed / platform.changed / context.changed / host.changed）。
 */
export type AppEvent = { "kind": "settingsChanged", revision: Revision, } | { "kind": "permissionsChanged", revision: Revision, } | { "kind": "platformChanged", revision: Revision, } | { "kind": "contextChanged", contextId: string, revision: Revision, } | { "kind": "hostStateChanged", state: HostState, } | { "kind": "sessionChanged", sessionId: string, revision: Revision, deleted: boolean, } | { "kind": "surfaceChanged", revision: Revision, } | { "kind": "terminalChanged", sessionId: string, revision: Revision, } | { "kind": "runChanged", runId: string, revision: Revision, } | { "kind": "rulesChanged", revision: Revision, } | { "kind": "favoritesChanged", revision: Revision, } | { "kind": "toolsChanged", toolId: string, } | { "kind": "providersChanged" };
