// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { FieldError } from "./FieldError";
import type { Revision } from "./Revision";

/**
 * 统一错误载荷：所有请求返回 `Result<T, AppError>`。
 */
export type AppError = { code: ErrorCode, message: string, retryable: boolean, fieldErrors?: Array<FieldError>,
/**
 * conflict 时携带宿主当前版本，便于窗口重拉快照。
 */
currentRevision?: Revision, };
