// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppUpdatePhase } from "./AppUpdatePhase";

/**
 * Update metadata only; download URLs and signatures remain in the host.
 */
export type AppUpdateStatus = { phase: AppUpdatePhase, version: string | null, notes: string | null, downloadedBytes: number, totalBytes: number | null, error: string | null, };
