// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工程构建信息。`app_build_info` 与 `app_bootstrap` 的载荷之一。
 */
export type BuildInfo = { productName: string, version: string, bundleIdentifier: string, stage: string, targetOs: string, targetArch: string, buildProfile: string, minimumMacosVersion: string, };
