// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityField } from "./CapabilityField";
import type { ContextSnapshot } from "./ContextSnapshot";

export type CapabilityForm = { capabilityId: string, context: ContextSnapshot, minimumInputs: number, fields: Array<CapabilityField>, changesFiles: boolean, };
