// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CapabilityField = { key: string, label: string, kind: string, defaultValue: string, required: boolean, choices: Array<string>, };
