// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextAvailability = { "kind": "available" } | { "kind": "noDirectory", reason: string, } | { "kind": "permissionRequired" } | { "kind": "finderNotRunning" } | { "kind": "selectionOverLimit", count: number, limit: number, } | { "kind": "failed", message: string, };
