// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextAvailability } from "./ContextAvailability";
import type { ContextSource } from "./ContextSource";
import type { PathRef } from "./PathRef";
import type { Revision } from "./Revision";
import type { ViewKind } from "./ViewKind";

export type ContextSnapshot = { id: string, revision: Revision, source: ContextSource, sourceWindowId: number | null, directoryRef: PathRef | null,
/**
 * 平台可提供的顺序；超限时为空。
 */
selectedItems: Array<PathRef>, viewKind: ViewKind, capturedAt: string, availability: ContextAvailability,
/**
 * false 表示选区因超限或读取失败而不完整。
 */
selectionComplete: boolean, };
