// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversion cleanup only runs after a verified new output exists.
 */
export type ConversionSourceHandling = "keep" | "trashAfterSuccess";
