// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryRole } from "./EntryRole";

export type ConversationEntry = { id: string, sessionId: string, role: EntryRole, content: string, runId: string | null, createdAt: string, };
