// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildInfo } from "./BuildInfo";
import type { CredentialStoreStatus } from "./CredentialStoreStatus";
import type { HostState } from "./HostState";
import type { PermissionSnapshot } from "./PermissionSnapshot";
import type { PlatformCapabilities } from "./PlatformCapabilities";
import type { StorageStatus } from "./StorageStatus";

/**
 * `diagnostics_get`：仅安全字段。
 */
export type DiagnosticsSnapshot = { buildInfo: BuildInfo, hostState: HostState, generation: string, storage: StorageStatus, logDirDisplay: string, appliedMigrations: Array<string>, permissions: PermissionSnapshot, platform: PlatformCapabilities, credentialStore: CredentialStoreStatus, };
