// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextSnapshot } from "./ContextSnapshot";

export type DirectoryPickResult = { "kind": "selected", snapshot: ContextSnapshot, } | { "kind": "cancelled" } | { "kind": "failed", message: string, };
