// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EffectKind = "read" | "create" | "copy" | "move" | "rename" | "modify" | "overwrite" | "trash" | "delete" | "networkWrite" | "systemChange" | "install" | "unknown";
