// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 稳定错误码（architecture.md §8）。
 */
export type ErrorCode = "forbidden" | "conflict" | "validation" | "unavailable" | "not_found" | "storage" | "platform" | "internal";
