// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepKind } from "./StepKind";

export type ExecutionStep = { kind: StepKind,
/**
 * native 步骤的操作名（如 fs.copy）；process/script 为空。
 */
operation: string,
/**
 * process 步骤的可执行文件路径。
 */
executableRef: string | null,
/**
 * script 步骤的显式脚本（解释器由计划声明）。
 */
script: string | null, args: Array<string>, cwdRef: string | null, envRefs: Array<string>, inputRefs: Array<string>, expectedOutputs: Array<string>, };
