// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";
import type { ExecutionStep } from "./ExecutionStep";
import type { PlanPreviewCompleteness } from "./PlanPreviewCompleteness";
import type { Revision } from "./Revision";

export type ExecutionPlan = { id: string, revision: Revision, capabilityId: string | null, contextId: string, steps: Array<ExecutionStep>, requiredTools: Array<string>, effects: Array<Effect>, previewCompleteness: PlanPreviewCompleteness, sourceFingerprint: string, };
