// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Favorite = { id: string, name: string,
/**
 * ai | manual：手动命令收藏保持手动来源（FR-FAV-002）。
 */
kind: string, content: string, tags: Array<string>, createdAt: string, lastUsedAt: string | null, };
