// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 字段级错误：`code` 为 `invalid`（越界/非法）或 `notAvailable`（当前阶段未开放）。
 */
export type FieldError = { field: string, code: string, message: string, };
