// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HotkeyModifier } from "./HotkeyModifier";

/**
 * 有效快捷键：只有宿主注册成功的候选才落到设置。`key` 为稳定键标识（W3C code）。
 */
export type Hotkey = { key: string, modifiers: Array<HotkeyModifier>, };
