// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolManifest } from "./ToolManifest";

/**
 * 已安装记录（installed_tools 表；重开应用后据此恢复状态）。
 */
export type InstalledTool = { manifest: ToolManifest, installedAt: string, installDir: string, };
