// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工具设施端口（FR-TOOLS-001..005）：探测、staging 下载安装与所有权卸载
 * 在适配层实现；取消经 AtomicBool 在下载块间生效。
 * 工具安装进度（FR-TOOLS-002 / AC-COMMON-008）：确定字节量与阶段状态区分。
 */
export type InstallProgress = { "stage": "download", bytes: number, total: number | null, } | { "stage": "verifying" } | { "stage": "extracting" } | { "stage": "publishing" } | { "stage": "installing", message: string, };
