// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathKind } from "./PathKind";

/**
 * 前端与模型只引用 `id`；`display_path` 是有损显示文本，不能往返执行。
 * Rust 端由 PathRegistry 绑定原始 PathBuf。
 */
export type PathRef = { id: string, displayPath: string, kind: PathKind, };
