// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "./Permission";
import type { PermissionProcedure } from "./PermissionProcedure";
import type { PermissionStatus } from "./PermissionStatus";
import type { RecoveryAction } from "./RecoveryAction";

export type PermissionRecord = { permission: Permission, status: PermissionStatus, procedure: PermissionProcedure,
/**
 * RFC 3339；Unknown 时为 None。
 */
checkedAt: string | null, error: string | null, recovery: RecoveryAction,
/**
 * 上一次为 Allowed、本次不再允许。
 */
revoked: boolean, };
