// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationState } from "./OperationState";
import type { Permission } from "./Permission";

/**
 * `permissions_request` 立即返回的操作句柄；结果经 permissions.changed 事件与快照异步更新。
 */
export type PermissionOperation = { operationId: string, permission: Permission, state: OperationState, startedAt: string, };
