// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionRecord } from "./PermissionRecord";
import type { Revision } from "./Revision";

export type PermissionSnapshot = { revision: Revision, records: Array<PermissionRecord>, };
