// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunRecord } from "./RunRecord";

/**
 * 规划结果：可执行计划已提交为 Run，或回退为摘要（FR-AI-008：不强制执行）。
 */
export type PlanOutcome = { "kind": "execute", run: RunRecord, } | { "kind": "summary", text: string,
/**
 * 摘要来自哪次尝试的原始回复（含失败重试说明）。
 */
attempts: number, };
