// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlatformCapability } from "./PlatformCapability";
import type { Revision } from "./Revision";

export type PlatformCapabilities = { revision: Revision, items: Array<PlatformCapability>, };
