// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityState } from "./CapabilityState";

export type PlatformCapability = {
/**
 * 稳定标识，如 `finderContext`、`accessibilityGeometry`、`directoryPicker`、`credentialStore`。
 */
id: string, state: CapabilityState, reason: string | null, recovery: string | null, };
