// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 端点记录（持久化形态；不含密钥）。协议首版只有 openai-compatible。
 */
export type ProviderRecord = { id: string, displayName: string, baseUrl: string, models: Array<string>, defaultGenerationModel: string | null, summaryModel: string | null, timeoutMs: number, };
