// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 保存请求（写路径）：api_key 为 None 表示保持现状；Some("") 表示清除密钥。
 */
export type ProviderSaveRequest = { id: string, displayName: string, baseUrl: string, models: Array<string>, defaultGenerationModel: string | null, summaryModel: string | null, timeoutMs: number, apiKey: string | null, };
