// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderRecord } from "./ProviderRecord";

/**
 * 列表条目（读路径）：记录 + 密钥是否已配置（掩码语义，不回传密钥）。
 */
export type ProviderView = { record: ProviderRecord, credentialConfigured: boolean, };
