// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderProtocol } from "./ProviderProtocol";

/**
 * 用户配置的模型端点；密钥只经 credentialRef 指向系统凭据，不在此结构中。
 */
export type ProviderConfig = { id: string, displayName: string, protocol: ProviderProtocol, baseUrl: string, models: Array<string>, defaultModel: string | null, summaryModel: string | null, timeoutMs: number, credentialRef: string | null, };
