// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from "./Revision";

export type QueuedLine = { requestId: string, sessionId: string, contextRevision: Revision,
/**
 * 提交时显示的目标目录（显示路径；宿主另持原生路径）。
 */
target: string, text: string, };
