// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from "./Revision";
import type { RuleScope } from "./RuleScope";

export type Rule = { id: string, name: string, content: string, enabled: boolean, scope: RuleScope, revision: Revision, createdAt: string, updatedAt: string, };
