// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RuleScope = { "kind": "global" } | { "kind": "directory", path: string, } | { "kind": "phrase", phrase: string, } | { "kind": "directoryAndPhrase", path: string, phrase: string, };
