// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiPolicyWire } from "./AiPolicyWire";
import type { ExecutionPlan } from "./ExecutionPlan";
import type { Revision } from "./Revision";
import type { RunOriginWire } from "./RunOriginWire";
import type { RunState } from "./RunState";
import type { RunStepResult } from "./RunStepResult";

/**
 * Run 记录（持久化 JSON 载荷；输出大块分段走 append_output）。
 */
export type RunRecord = { id: string, sessionId: string, parentRunId: string | null, origin: RunOriginWire, prompt: string, contextId: string, planRevision: Revision, state: RunState, policy: AiPolicyWire,
/**
 * 内存输出缓冲（持久化截断由 append_output 分段负责）。
 */
output: string, exitStatus: number | null, createdAt: string, updatedAt: string, plan: ExecutionPlan | null, stepResults: Array<RunStepResult>, directoryDisplay: string, requestId: string | null, requestFingerprint: string, approvalRequestId: string | null, };
