// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Run 状态（FR-RUN-001）：摘要状态独立于 Run 状态。
 */
export type RunState = "planning" | "awaitingInput" | "awaitingApproval" | "installing" | "queued" | "running" | "succeeded" | "partiallySucceeded" | "failed" | "cancelled" | "interrupted";
