// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunState } from "./RunState";

export type RunStepResult = { index: number, state: RunState, exitStatus: number | null, message: string, };
