// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectorySync } from "./DirectorySync";
import type { Revision } from "./Revision";
import type { SessionState } from "./SessionState";

export type Session = { id: string, parentSessionId: string | null, title: string, state: SessionState, initialDirectory: string | null, currentDirectory: string | null, targetDirectory: string | null, directorySync: DirectorySync, terminalId: string | null, pinned: boolean, createdAt: string, lastUsedAt: string, endedAt: string | null, revision: Revision, };
