// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Activation } from "./Activation";
import type { AiPolicy } from "./AiPolicy";
import type { ConversionSourceHandling } from "./ConversionSourceHandling";
import type { HideBehavior } from "./HideBehavior";
import type { Hotkey } from "./Hotkey";
import type { MotionMode } from "./MotionMode";
import type { NameConflict } from "./NameConflict";
import type { OutputLocation } from "./OutputLocation";
import type { ProviderConfig } from "./ProviderConfig";
import type { Revision } from "./Revision";
import type { SummaryModel } from "./SummaryModel";
import type { Theme } from "./Theme";

/**
 * 已提交的设置快照：`persisted=false` 表示存储不可用时的临时默认值（未持久化）。
 */
export type SettingsSnapshot = { revision: Revision, persisted: boolean, barEnabled: boolean, activation: Activation, hotkey: Hotkey | null, hideBehavior: HideBehavior, aiPolicy: AiPolicy, launchAtLogin: boolean, theme: Theme,
/**
 * 1–30 秒；None 表示常驻。
 */
bubbleSeconds: number | null, inlineSuggestionsEnabled: boolean,
/**
 * 1–5。
 */
inlineSuggestionsLimit: number, transparency: boolean, motionMode: MotionMode, providers: Array<ProviderConfig>, defaultModel: string | null, summaryModel: SummaryModel,
/**
 * 11–20。
 */
terminalFontSize: number, outputLocation: OutputLocation, nameConflict: NameConflict, conversionSourceHandling: ConversionSourceHandling, };
