// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Revision } from "./Revision";
import type { SettingsPatch } from "./SettingsPatch";

/**
 * `settings_update` 请求：变更携带 requestId 与 expectedRevision（architecture.md §8）。
 */
export type SettingsUpdateRequest = { requestId: string, expectedRevision: Revision, patch: SettingsPatch, };
