// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Activation } from "./Activation";
import type { AiPolicy } from "./AiPolicy";
import type { ConversionSourceHandling } from "./ConversionSourceHandling";
import type { HideBehavior } from "./HideBehavior";
import type { Hotkey } from "./Hotkey";
import type { MotionMode } from "./MotionMode";
import type { NameConflict } from "./NameConflict";
import type { OutputLocation } from "./OutputLocation";
import type { ProviderConfig } from "./ProviderConfig";
import type { SummaryModel } from "./SummaryModel";
import type { Theme } from "./Theme";

/**
 * 设置补丁：每个字段可缺省；可空字段区分缺省与显式 null。
 */
export type SettingsPatch = { barEnabled?: boolean, activation?: Activation, hotkey?: Hotkey | null | null, hideBehavior?: HideBehavior, aiPolicy?: AiPolicy, launchAtLogin?: boolean, theme?: Theme, bubbleSeconds?: number | null | null, inlineSuggestionsEnabled?: boolean, inlineSuggestionsLimit?: number, transparency?: boolean, motionMode?: MotionMode, providers?: Array<ProviderConfig>, defaultModel?: string | null | null, summaryModel?: SummaryModel, terminalFontSize?: number, outputLocation?: OutputLocation, conversionSourceHandling?: ConversionSourceHandling, nameConflict?: NameConflict, };
