// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageState } from "./StorageState";

export type StorageStatus = { state: StorageState, dataDirDisplay: string, schemaVersion: number, message: string | null,
/**
 * 迁移前备份文件（显示路径），无则 None。
 */
lastBackupDisplay: string | null, };
