// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectorySync } from "./DirectorySync";
import type { ShellReadinessState } from "./ShellReadinessState";
import type { TerminalSize } from "./TerminalSize";
import type { TerminalState } from "./TerminalState";

export type TerminalSnapshot = { terminalId: string, sessionId: string, state: TerminalState, shell: string, size: TerminalSize, shellReadiness: ShellReadinessState, foregroundProcess: string | null, currentDirectory: string, pendingDirectory: string | null, directorySync: DirectorySync,
/**
 * 屏幕恢复数据：主屏/备用屏 + 光标（xterm 以此重建）。
 */
screen: string,
/**
 * 十进制字符串序号；订阅从此处继续。
 */
streamCursor: string, exitStatus: number | null,
/**
 * 持久输出是否已截断（超过 100 MiB 限额）。
 */
truncated: boolean, };
