// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledTool } from "./InstalledTool";
import type { ToolManifest } from "./ToolManifest";
import type { ToolStatus } from "./ToolStatus";

/**
 * tools_list 条目：清单 + 当前真实状态 + 已安装记录（UI-TOOLS 展示来源）。
 */
export type ToolEntry = { manifest: ToolManifest, status: ToolStatus, installed: InstalledTool | null, };
