// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工具来源：受管包必须给出 URL 与 SHA-256；系统工具仅探测。
 */
export type ToolSource = { "kind": "managed", url: string, sha256: string, } | { "kind": "system" };
