// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallProgress } from "./InstallProgress";

export type ToolPreparation = { running: boolean, cancelled: boolean, completed: number, total: number, currentTool: string | null, progress: InstallProgress | null, errors: Array<string>, };
