// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工具所有者：Fleqi 受管安装或用户系统已有（architecture.md §9.2）。
 */
export type ToolOwner = "fleqi" | "system";
