// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolOwner } from "./ToolOwner";

/**
 * 工具状态：检测中由 UI 表达；这里只有可判定的三种结果。
 */
export type ToolStatus = { "kind": "available", version: string, owner: ToolOwner, path: string, } | { "kind": "notInstalled" } | { "kind": "unavailable", reason: string, };
