// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolSource } from "./ToolSource";

/**
 * 工具清单：版本、平台映射与检测方式由受管目录确定（FR-TOOLS-005）。
 */
export type ToolManifest = { id: string, version: string, platform: string, arch: string,
/**
 * 受管包内可执行文件相对路径；系统工具为可执行名（PATH 查找）。
 */
executable: string, source: ToolSource, license: string | null,
/**
 * 依赖此工具的能力 ID（用于影响展示）。
 */
capabilities: Array<string>,
/**
 * 检测参数（如 `--version`），退出码 0 视为可用。
 */
detectionArgs: Array<string>, };
